[package]
name = "tuneo-linux"
version = "0.1.0"
edition = "2021"

[dependencies]
gtk4 = "0.9"
libadwaita = "0.7"
tuneo-native-core = { path = "../../packages/native-core" }
tokio = { version = "1", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
